### PR TITLE
fix typos and accents in the post

### PR DESCRIPTION
**Pull request by ioviedodev**
Por favor revisar estos cambios

- [x] Testear
- [x] Revisar

### CODE REVIEW

**Review by doviedodev — CHANGES_REQUESTED** [review]
Please use html for accents, preview to approve

**Comment by ioviedodev** [comment]
@doviedodev the change was made

**Review by doviedodev — APPROVED** [review]
No more comments, it is ok.

**Comment by ioviedodev** [comment]
Ok, I proceed with a merge

**Pull request merged**
